name: wechat_assets_picker_demo
description: The demo project for the wechat_assets_picker package.
version: 8.0.0+20
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^3.2.0

  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.8
  provider: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
