name: wechat_assets_picker_demo
description: The demo project for the wechat_assets_picker package.
version: 6.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^2.4.0

  extended_image: ^5.1.0
  package_info_plus: ^1.0.6
  path: ^1.8.0
  path_provider: ^2.0.4
  provider: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
