name: wechat_assets_picker
version: 8.4.2
description: |
  An image picker (also with videos and audio)
  for Flutter projects based on WeChat's UI,
  with full support for customization.

repository: https://github.com/fluttercandies/flutter_wechat_assets_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_assets_picker/issues

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^7.0.0
  photo_manager: ^2.4.0
  provider: ^6.0.2
  video_player: ^2.4.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Screenshot 1'
    path: screenshots/README_1.webp
  - description: 'Screenshot 2'
    path: screenshots/README_2.webp
  - description: 'Screenshot 3'
    path: screenshots/README_3.webp
  - description: 'Screenshot 4'
    path: screenshots/README_4.webp
  - description: 'Screenshot 5'
    path: screenshots/README_5.webp
  - description: 'Screenshot 6'
    path: screenshots/README_6.webp
  - description: 'Screenshot 7'
    path: screenshots/README_7.webp
  - description: 'Screenshot 8'
    path: screenshots/README_8.webp
  - description: 'Screenshot 9'
    path: screenshots/README_9.webp
