name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 5.0.0-dev.4
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^1.5.0
  photo_manager: ^0.6.0
  provider: ^4.3.3
  video_player: ^1.0.1
