name: wechat_assets_picker
description: An assets picker in pure dart which looks like the one in WeChat, support multi asset pick from device.
version: 1.3.2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^0.7.1
  photo_manager: ^0.5.1-dev.3
  provider: ^4.0.2
  video_player: ^0.10.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
