name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 5.0.0-dev.3
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^1.1.2
  photo_manager: ">=0.6.0-dev.8 <2.0.0"
  provider: ^4.3.2+2
  video_player: ">=0.11.0 <2.0.0"
