name: wechat_assets_picker
description: An assets picker in pure dart which looks like the one in WeChat, support multi asset pick from device.
version: 1.7.0-dev.2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ">=0.7.4 <2.0.0"
  photo_manager: ">=0.5.2 <2.0.0"
  provider: ">=4.1.2 <5.0.0"
  video_player: ">=0.10.11 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
