name: wechat_assets_picker
description: |
  An audio/video/image picker in pure Dart which is the same with WeChat,
  support multi picking, custom item and delegates override.
repository: https://github.com/fluttercandies/flutter_wechat_assets_picker
version: 8.1.3

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^6.2.0
  photo_manager: ^2.4.0
  provider: ^6.0.2
  video_player: ^2.4.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
