name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 6.2.4
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^5.1.0
  photo_manager: ^1.3.4
  provider: ^6.0.1
  video_player: ^2.2.3
